name: chat_messenger
description: A simple chat messenger build using Flutter and Firebase.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">= 2.10.0 < 3.0.0"
  flutter: ">= 1.22.0 < 2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^4.3.2
  shared_preferences: ^0.5.6
  image_picker: ^0.6.7
  # google
  firebase_auth: ^0.18.2
  cloud_firestore: ^0.14.2
  firebase_storage: ^4.0.1
  # third party
  adaptive_library: ^0.5.4
  uuid: ^2.2.2
  dash_chat: ^1.1.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flappy_translator: ^1.5.0

flutter:
  uses-material-design: true
  
# settings for flappy_translator package
flappy_translator:
  input_file_path: "assets_dev/loca/loca.csv"
  output_dir: "lib"
  file_name: "i18n"
  class_name: "I18n"
  delimiter: ";"
  start_index: 2
  depend_on_context: false
  use_single_quotes: true
  replace_no_break_spaces: false