name: chat_messenger
description: A simple chat messenger build using Flutter and Firebase.
version: 0.0.1+1
author: James Leahy <defuncart@gmail.com>

environment:
  sdk: 2.7.0
  flutter: 1.12.13+hotfix.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  