name: chat_messenger
description: A simple chat messenger build using Flutter and Firebase.
version: 0.0.1+1
author: James Leahy <defuncart@gmail.com>

environment:
  sdk: 2.7.0
  flutter: 1.12.13+hotfix.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 0.1.3
  provider: 4.0.1
  shared_preferences: 0.5.6
  image_picker: 0.6.2+3
  # google
  firebase_auth: 0.15.3
  cloud_firestore: 0.13.0+1
  firebase_storage: 3.1.1
  # third party
  adaptive_library:
    git:
      url: https://github.com/defuncart/adaptive_library
      ref: feature/add-localization-settings-adaptive-app
  uuid: 2.0.4
  dash_chat: ^1.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flappy_translator: 1.2.0

flutter:
  uses-material-design: true
  
# settings for flappy_translator package
flappy_translator:
  input_file_path: "assets-dev/loca/loca.csv"
  output_dir: "lib"
  file_name: "i18n"
  class_name: "I18n"
  delimiter: ";"
  start_index: 2
  depend_on_context: false
  use_single_quotes: true
  replace_no_break_spaces: false